on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Testing GitHub action
    steps:
    - name: install-cpm
      id: installcpm
      uses: perl-actions/install-cpm@master
      with:
        who-to-greet: 'some args'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.installcpm.outputs.time }}"